// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBak0qmuKfCa6QYCs4qnU8-GXcJ9PtTSbc',
    appId: '1:692545130750:web:7b07c0ba4ba00112fad5af',
    messagingSenderId: '692545130750',
    projectId: 'gym-application-c71bb',
    authDomain: 'gym-application-c71bb.firebaseapp.com',
    storageBucket: 'gym-application-c71bb.firebasestorage.app',
    measurementId: 'G-PLPWYRZZTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSku2s-OI1uPwvPJfyp4FfZOLgV2ur1ks',
    appId: '1:692545130750:android:394f9b16dec8e0c1fad5af',
    messagingSenderId: '692545130750',
    projectId: 'gym-application-c71bb',
    storageBucket: 'gym-application-c71bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiRllENsJzv9VWS_5EDTyWhmsQWIoSa8U',
    appId: '1:692545130750:ios:53a9edca6e6b81f6fad5af',
    messagingSenderId: '692545130750',
    projectId: 'gym-application-c71bb',
    storageBucket: 'gym-application-c71bb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiRllENsJzv9VWS_5EDTyWhmsQWIoSa8U',
    appId: '1:692545130750:ios:53a9edca6e6b81f6fad5af',
    messagingSenderId: '692545130750',
    projectId: 'gym-application-c71bb',
    storageBucket: 'gym-application-c71bb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBak0qmuKfCa6QYCs4qnU8-GXcJ9PtTSbc',
    appId: '1:692545130750:web:c2c16c2c0c0e64dcfad5af',
    messagingSenderId: '692545130750',
    projectId: 'gym-application-c71bb',
    authDomain: 'gym-application-c71bb.firebaseapp.com',
    storageBucket: 'gym-application-c71bb.firebasestorage.app',
    measurementId: 'G-XMP73DFQ75',
  );
}
